// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, created_at, updated_at, email, hashed_password)
VALUES (
    gen_random_uuid(),
    NOW(),
    NOW(),
    $1,
    $2
)
RETURNING id, created_at, updated_at, email, hashed_password
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email, hashed_password FROM users
WHERE email = $1
`

func (q *Queries) GetUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.HashedPassword,
	)
	return i, err
}

const resetDB = `-- name: ResetDB :exec
DELETE FROM users
`

func (q *Queries) ResetDB(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetDB)
	return err
}

const updateUserUpdatedAtTime = `-- name: UpdateUserUpdatedAtTime :one
UPDATE users
SET updated_at = NOW()
WHERE id = $1
RETURNING users.updated_at
`

func (q *Queries) UpdateUserUpdatedAtTime(ctx context.Context, id uuid.UUID) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, updateUserUpdatedAtTime, id)
	var updated_at time.Time
	err := row.Scan(&updated_at)
	return updated_at, err
}
